# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "dHFV391LHQZC66B980/VgacNXf2mYKwy71oqQTwDb0L2WKXrtRwoTqdj5PtPB07j8EH5T8ATTTeyi5hsLNppBBHg0cJZA0lLSIM9mHCO0NGNocQRorwWQFIH43ndpfmWig8SIgSD7O5XKeOYKBgAQF3BLWAvl22BAvd5K0lqpzMaJNwxLNELUYf/s4g6UR2sOEWwP5lIFVS/x3ma4c9xTc1Ky+M6iGfwQaHH1tfpL3/9FeIFDu0uOYD4AQXjnnp+AzxRHVNwy48k37NmgDyz4AF+h3IK+Z1BRn0yZLxByKIoTSbzme79M1HVXBGVikGS6vIiNTiUDnhrT7lQeA8qPgsvFbH02pNYbOPknxOdVEUiU/M+0I4hIEjMRy9F1opbfzmu3nI+VBtEVBLwPurRMEk4kdZYCi9zfaUPSUP97fTmmJTaUyLuGk/vgsZ6Nr33D6m03GgcHZ4YMd1uF//+aSc8P+6nmjEjQaat7Jb3AEyXJEDd+h2NifGjdlx494HB1fFzFmfSklT/vC52GBT1BTujXWTwQFiFKEzkt5AGULEc/oMMT1J0Gxj7faNPdKsRdn9Hu+7MDzWYxHJJGP6A8oBq6Q+9+JFyMMYrd5I8CKpRwPo/+6TO/iGNfSGyj/rcoz+U/cfJCJbDL9ZkAakTQmbjEOPI9nEb1ZDzyCU+A48="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
