travis:
  secure:
    BINSTAR_TOKEN: dHFV391LHQZC66B980/VgacNXf2mYKwy71oqQTwDb0L2WKXrtRwoTqdj5PtPB07j8EH5T8ATTTeyi5hsLNppBBHg0cJZA0lLSIM9mHCO0NGNocQRorwWQFIH43ndpfmWig8SIgSD7O5XKeOYKBgAQF3BLWAvl22BAvd5K0lqpzMaJNwxLNELUYf/s4g6UR2sOEWwP5lIFVS/x3ma4c9xTc1Ky+M6iGfwQaHH1tfpL3/9FeIFDu0uOYD4AQXjnnp+AzxRHVNwy48k37NmgDyz4AF+h3IK+Z1BRn0yZLxByKIoTSbzme79M1HVXBGVikGS6vIiNTiUDnhrT7lQeA8qPgsvFbH02pNYbOPknxOdVEUiU/M+0I4hIEjMRy9F1opbfzmu3nI+VBtEVBLwPurRMEk4kdZYCi9zfaUPSUP97fTmmJTaUyLuGk/vgsZ6Nr33D6m03GgcHZ4YMd1uF//+aSc8P+6nmjEjQaat7Jb3AEyXJEDd+h2NifGjdlx494HB1fFzFmfSklT/vC52GBT1BTujXWTwQFiFKEzkt5AGULEc/oMMT1J0Gxj7faNPdKsRdn9Hu+7MDzWYxHJJGP6A8oBq6Q+9+JFyMMYrd5I8CKpRwPo/+6TO/iGNfSGyj/rcoz+U/cfJCJbDL9ZkAakTQmbjEOPI9nEb1ZDzyCU+A48=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
